### ISSUE TITLE
gl mt3000使用immortalwrt 23.05.2启用后风扇不启动

### ISSUE THREAD

**Issue by m0eak** [JiaY-shi/fancontrol#1]
安装后设置为了60度，风扇确实停了，但是到了66度还没有开始转
编译好的固件已经有kmod-hwmon-core 和kmod-hwmon-pwmfan，是我操作不对吗

**Comment by JiaY-shi** [comment]
贴下配置

**Comment by m0eak** [comment]
.config吗 

 

 




 
 
  
 
  ----- 原始邮件 -----
  
发件人：shi ***@***.***>
  
***@***.***>等3人
  
主题：Re:_[JiaY-shi/fancontrol]_gl_mt3000使用immortalwrt_23.05.2启用后风扇不启动_(Issue_#1)
  
日期：2024年04月13日 20:22:36
  

 
 
 
  
 贴下配置

**Comment by m0eak** [comment]
[mt3000.txt](https://github.com/JiaY-shi/fancontrol/files/14967434/mt3000.txt)

**Comment by JiaY-shi** [comment]
不不不，是fancontrol的配置

**Comment by m0eak** [comment]
![image](https://github.com/JiaY-shi/fancontrol/assets/50049180/d03ae7e5-830e-4a0c-9f34-7a3c7a699bd3)
`

       config fancontrol 'settings'

	option enabled '1'

	option thermal_file '/sys/devices/virtual/thermal/thermal_zone0/temp'

	option fan_file '/sys/devices/virtual/thermal/cooling_device0/cur_state'

	option start_temp '60'

	option start_speed '35'

	option max_speed '255'

	option temp_div '1000'

`

**Comment by JiaY-shi** [comment]
fan_file可以写么？手动echo转速试试

**Comment by m0eak** [comment]
echo 35 /sys/devices/virtual/thermal/cooling_device0/cur_state
后
cat还是0

**Comment by JiaY-shi** [comment]
稍等，我看下immortalwrt源码

更新:明天看吧，今天太晚了，大概率是dts中限制了风扇的level

**Comment by m0eak** [comment]
> 稍等，我看下immortalwrt源码
> 
> 更新:明天看吧，今天太晚了，大概率是dts中限制了风扇的level

好的，谢谢大佬

**Comment by JiaY-shi** [comment]
看了一下，果然是dts限制了，`cooling-levels = <0 63 95 127 159 191 223 255>`，你可以改下，改的细一点，就像我仓库里axt1800定义的一样。
后续考虑把该项目改成读dts中的cooling-levels的值。

**Comment by m0eak** [comment]
> 看了一下，果然是dts限制了，`cooling-levels = <0 63 95 127 159 191 223 255>`，你可以改下，改的细一点，就像我仓库里axt1800定义的一样。 后续考虑把该项目改成读dts中的cooling-levels的值。

改immortalwrt源码里的这行吗

**Comment by m0eak** [comment]
> 看了一下，果然是dts限制了，`cooling-levels = <0 63 95 127 159 191 223 255>`，你可以改下，改的细一点，就像我仓库里axt1800定义的一样。 后续考虑把该项目改成读dts中的cooling-levels的值。

0-255全填满了，能用了
