### ISSUE TITLE
插件没有作用

### ISSUE THREAD

**Issue by King-Of-Knights** [JiaY-shi/fancontrol#2]
佬好呀，我的设备是AXT1800，编译的是您的AXT1800仓库，风扇可以转起来，但是我感觉这个插件没法控制风扇，首先实时转速读取不出来，另外设置启动温度对风扇开关好像没有影响，以下是配置图
![微信截图_20240419190842](https://github.com/JiaY-shi/fancontrol/assets/25562792/23b9e52a-e297-4b9e-8861-d90c44952c5a)

**Comment by JiaY-shi** [comment]
贴一下fancontrol完整的配置

**Comment by King-Of-Knights** [comment]
@JiaY-shi 
```
config fancontrol 'settings'
	option enabled '1'
	option thermal_file '/sys/devices/virtual/thermal/thermal_zone0/temp'
	option fan_file '/sys/devices/virtual/thermal/cooling_device0/cur_state'
	option start_temp '50'
	option start_speed '35'
	option max_speed '255'
	option temp_div '1000
```

**Comment by JiaY-shi** [comment]
cooling_device0改成cooling_device1试试

**Comment by King-Of-Knights** [comment]
It works! Thx!

**Comment by King-Of-Knights** [comment]
狼人大佬好，随着固件的更新，似乎这个插件又失去了作用，目前是风扇可以转起来，但是无法通过插件关闭风扇，我的配置如下：
```
config fancontrol 'settings'
	option enabled '1'
	option thermal_file '/sys/devices/virtual/thermal/thermal_zone0/temp'
	option fan_file '/sys/devices/virtual/thermal/cooling_device1/cur_state'
	option start_temp '50'
	option start_speed '35'
	option max_speed '255'
	option temp_div '1000'

```
假设机器的温度为55°，将start_temp设置为60°，`cur_state`文件显示为0，风扇仍然会转起来。将start_temp设置为50°，`cur_state`文件显示为59，风扇仍然转起来，似乎不受`cur_state`文件控制了

**Comment by JiaY-shi** [comment]
`fan_file` 尝试着改成`/sys/devices/virtual/thermal/cooling_device0/cur_state`试试呢，有空我也试试

**Comment by King-Of-Knights** [comment]
> `fan_file` 尝试着改成`/sys/devices/virtual/thermal/cooling_device0/cur_state`试试呢，有空我也试试

我大概看了一下狼大的实现方法，似乎是通过实时修改cur_state文件控制转速。在我的机器上，这个程序确实修改了`cur_state`，也显示在Luci上。我确定编译的config里面有config_pwm等三项，狼大的这个插件里，是否有特殊依赖项，我没有加进去呢？

**Comment by JiaY-shi** [comment]
没有其它依赖，你可以手动echo 值到cooling_device*/cur_state文件中看看哪个有效

**Comment by King-Of-Knights** [comment]
我尝试了一下，我用`echo 0 >  /sys/devices/virtual/thermal/cooling_device1/cur_state`, 然后用cat读取，`cat /sys/devices/virtual/thermal/cooling_device1/cur_state` 结果返回是0，但是风扇还在转的。
以下三项都开着，是否会影响结果呢？
```
CONFIG_PWM=y
CONFIG_PWM_IPQ=y
CONFIG_PWM_SYSFS=y
```
我看`/sys/devices/virtual/thermal/cooling_device1/type`中的结果是`ath11k_thermal`,这个是否有影响呢？

**Comment by King-Of-Knights** [comment]
我对比了一下原来可以用的版本，和现在不能用的版本，可以用的版本type显示是`pwm-fan`，而不能用的版本显示是‘ath11k_thermal‘；或者说`pwm-fan`没有显示出来，因为我这边原来有四个cooling_device, 现在只有三个了

**Comment by King-Of-Knights** [comment]
已解决，编译的项目没有pwm的驱动，加入[1008补丁](https://github.com/JiaY-shi/openwrt/blob/ipq60xx-devel_nss/target/linux/qualcommax/patches-6.6/1008-pwm-driver-for-qualcomm-ipq6018-pwm-block.patch)就正常使用了
