### ISSUE TITLE
畅网 N100 P5 + iStoreOS  添加不上 feed

### ISSUE THREAD

**Issue by liuformat** [JiaY-shi/fancontrol#3]
<img width="1636" alt="截屏2024-11-04 23 01 57" src="https://github.com/user-attachments/assets/e210512f-a7a7-489e-b2f0-bf1fc021bf33">
如图，这是不是添加不了 feed，还是没有 package，
有没有直接的 package 包呢？

**Comment by JiaY-shi** [comment]
README中给的安装步骤是用在源码编译安装的时候，而不是给已经编译好的固件中安装的。

**Comment by liuformat** [comment]
辛苦大佬的回复，那有什么办法可以直接安装呢？
本人小白，刚刚入门
