### ISSUE TITLE
当Web服务器为NGINX时，打不开插件管理页

### ISSUE THREAD

**Issue by XMing673** [JiaY-shi/fancontrol#6]
web服务器为NGINX时，打开插件页面会提示Error：XHR request aborted by browser，uhttpd则不存在这个问题
![image](https://github.com/user-attachments/assets/f788ef6f-9252-4f1c-be68-1243947d050b)

相关的日志好像就这一条
Fri Dec  6 17:33:35 2024 daemon.err nginx[4131]: 2024/12/06 17:33:35 [error] 4175#0: *45 upstream prematurely closed connection while reading upstream, client: 192.168.8.238, server: openwrt/, request: "POST /cgi-bin/cgi-download?1733477599612 HTTP/1.1", upstream: "uwsgi://unix:////var/run/luci-cgi_io.socket:", host: "192.168.8.1", referrer: "http://192.168.8.1/cgi-bin/luci/admin/services/fancontrol"

**Comment by JiaY-shi** [comment]
插件无关

**Comment by jjss520** [comment]
换成uhttpd就行
